import { Sql } from 'postgres';

export type IngredientComboPair = {
  comboId: number | null;
  ingredientId: number | null;
};

export type IngredientComboPairWithId = {
  id: number;
  comboId: number | null;
  ingredientId: number | null;
};

export const ingredientComboPairs: IngredientComboPair[] = [
  { comboId: 1, ingredientId: 2 },
  { comboId: 1, ingredientId: 62 },
  { comboId: 1, ingredientId: 134 },
  { comboId: 1, ingredientId: 51 },
  { comboId: 2, ingredientId: 2 },
  { comboId: 2, ingredientId: 140 },
  { comboId: 2, ingredientId: 25 },
  { comboId: 2, ingredientId: 141 },
  { comboId: 2, ingredientId: 48 },
  { comboId: 3, ingredientId: 3 },
  { comboId: 3, ingredientId: 31 },
  { comboId: 3, ingredientId: 49 },
  { comboId: 3, ingredientId: 21 },
  { comboId: 3, ingredientId: 48 },
  { comboId: 3, ingredientId: 136 },
  { comboId: 4, ingredientId: 4 },
  { comboId: 4, ingredientId: 48 },
  { comboId: 4, ingredientId: 142 },
  { comboId: 4, ingredientId: 52 },
  { comboId: 5, ingredientId: 4 },
  { comboId: 5, ingredientId: 42 },
  { comboId: 5, ingredientId: 52 },
  { comboId: 5, ingredientId: 48 },
  { comboId: 5, ingredientId: 33 },
  { comboId: 5, ingredientId: 111 },
  { comboId: 6, ingredientId: 6 },
  { comboId: 6, ingredientId: 50 },
  { comboId: 6, ingredientId: 98 },
  { comboId: 6, ingredientId: 21 },
  { comboId: 6, ingredientId: 48 },
  { comboId: 7, ingredientId: 6 },
  { comboId: 7, ingredientId: 19 },
  { comboId: 7, ingredientId: 99 },
  { comboId: 7, ingredientId: 110 },
  { comboId: 7, ingredientId: 134 },
  { comboId: 8, ingredientId: 5 },
  { comboId: 8, ingredientId: 21 },
  { comboId: 8, ingredientId: 25 },
  { comboId: 8, ingredientId: 122 },
  { comboId: 8, ingredientId: 48 },
  { comboId: 9, ingredientId: 5 },
  { comboId: 9, ingredientId: 48 },
  { comboId: 9, ingredientId: 58 },
  { comboId: 9, ingredientId: 91 },
  { comboId: 9, ingredientId: 102 },
  { comboId: 9, ingredientId: 70 },
  { comboId: 10, ingredientId: 7 },
  { comboId: 10, ingredientId: 55 },
  { comboId: 10, ingredientId: 56 },
  { comboId: 10, ingredientId: 124 },
  { comboId: 10, ingredientId: 22 },
  { comboId: 10, ingredientId: 127 },
  { comboId: 10, ingredientId: 61 },
  { comboId: 11, ingredientId: 7 },
  { comboId: 11, ingredientId: 60 },
  { comboId: 11, ingredientId: 62 },
  { comboId: 11, ingredientId: 126 },
  { comboId: 11, ingredientId: 135 },
  { comboId: 11, ingredientId: 51 },
  { comboId: 11, ingredientId: 134 },
  { comboId: 12, ingredientId: 1 },
  { comboId: 12, ingredientId: 15 },
  { comboId: 12, ingredientId: 21 },
  { comboId: 12, ingredientId: 49 },
  { comboId: 12, ingredientId: 76 },
  { comboId: 13, ingredientId: 1 },
  { comboId: 13, ingredientId: 20 },
  { comboId: 13, ingredientId: 64 },
  { comboId: 13, ingredientId: 126 },
  { comboId: 14, ingredientId: 3 },
  { comboId: 14, ingredientId: 12 },
  { comboId: 14, ingredientId: 81 },
  { comboId: 14, ingredientId: 20 },
  { comboId: 14, ingredientId: 21 },
  { comboId: 14, ingredientId: 84 },
  { comboId: 15, ingredientId: 8 },
  { comboId: 15, ingredientId: 12 },
  { comboId: 15, ingredientId: 111 },
  { comboId: 15, ingredientId: 48 },
  { comboId: 16, ingredientId: 8 },
  { comboId: 16, ingredientId: 68 },
  { comboId: 16, ingredientId: 30 },
  { comboId: 16, ingredientId: 105 },
  { comboId: 17, ingredientId: 9 },
  { comboId: 17, ingredientId: 29 },
  { comboId: 17, ingredientId: 30 },
  { comboId: 17, ingredientId: 129 },
  { comboId: 17, ingredientId: 21 },
  { comboId: 17, ingredientId: 8 },
  { comboId: 17, ingredientId: 105 },
  { comboId: 18, ingredientId: 9 },
  { comboId: 18, ingredientId: 21 },
  { comboId: 18, ingredientId: 64 },
  { comboId: 18, ingredientId: 126 },
  { comboId: 18, ingredientId: 102 },
  { comboId: 18, ingredientId: 48 },
  { comboId: 18, ingredientId: 128 },
  { comboId: 19, ingredientId: 1 },
  { comboId: 19, ingredientId: 11 },
  { comboId: 19, ingredientId: 12 },
  { comboId: 19, ingredientId: 114 },
  { comboId: 39, ingredientId: 2 },
  { comboId: 39, ingredientId: 20 },
  { comboId: 39, ingredientId: 35 },
  { comboId: 39, ingredientId: 48 },
  { comboId: 39, ingredientId: 64 },
  { comboId: 49, ingredientId: 3 },
  { comboId: 49, ingredientId: 28 },
  { comboId: 49, ingredientId: 1 },
  { comboId: 49, ingredientId: 64 },
  { comboId: 49, ingredientId: 33 },
  { comboId: 57, ingredientId: 3 },
  { comboId: 57, ingredientId: 35 },
  { comboId: 57, ingredientId: 85 },
  { comboId: 57, ingredientId: 8 },
  { comboId: 57, ingredientId: 64 },

  { comboId: 59, ingredientId: 4 },
  { comboId: 59, ingredientId: 39 },
  { comboId: 59, ingredientId: 121 },
  { comboId: 59, ingredientId: 48 },
  { comboId: 68, ingredientId: 5 },
  { comboId: 68, ingredientId: 21 },
  { comboId: 68, ingredientId: 22 },
  { comboId: 68, ingredientId: 77 },
  { comboId: 69, ingredientId: 5 },
  { comboId: 69, ingredientId: 25 },
  { comboId: 69, ingredientId: 21 },
  { comboId: 69, ingredientId: 122 },
  { comboId: 69, ingredientId: 133 },
  { comboId: 79, ingredientId: 6 },
  { comboId: 79, ingredientId: 21 },
  { comboId: 79, ingredientId: 22 },
  { comboId: 79, ingredientId: 118 },
  { comboId: 83, ingredientId: 6 },
  { comboId: 83, ingredientId: 34 },
  { comboId: 83, ingredientId: 49 },
  { comboId: 84, ingredientId: 6 },
  { comboId: 84, ingredientId: 51 },
  { comboId: 84, ingredientId: 101 },
  { comboId: 84, ingredientId: 77 },
  { comboId: 87, ingredientId: 7 },
  { comboId: 87, ingredientId: 53 },
  { comboId: 87, ingredientId: 56 },
  { comboId: 87, ingredientId: 22 },
  { comboId: 87, ingredientId: 61 },
  { comboId: 87, ingredientId: 137 },
  { comboId: 96, ingredientId: 7 },
  { comboId: 96, ingredientId: 58 },
  { comboId: 96, ingredientId: 62 },
  { comboId: 96, ingredientId: 51 },
  { comboId: 96, ingredientId: 134 },
  { comboId: 119, ingredientId: 8 },
  { comboId: 119, ingredientId: 64 },
  { comboId: 119, ingredientId: 34 },
  { comboId: 119, ingredientId: 48 },
  { comboId: 119, ingredientId: 139 },
  { comboId: 119, ingredientId: 105 },
  { comboId: 120, ingredientId: 8 },
  { comboId: 120, ingredientId: 58 },
  { comboId: 120, ingredientId: 51 },
  { comboId: 123, ingredientId: 9 },
  { comboId: 123, ingredientId: 11 },
  { comboId: 123, ingredientId: 82 },
  { comboId: 123, ingredientId: 8 },
  { comboId: 123, ingredientId: 102 },
  { comboId: 123, ingredientId: 70 },
  { comboId: 126, ingredientId: 9 },
  { comboId: 126, ingredientId: 12 },
  { comboId: 126, ingredientId: 25 },
  { comboId: 126, ingredientId: 128 },
  { comboId: 129, ingredientId: 9 },
  { comboId: 129, ingredientId: 19 },
  { comboId: 129, ingredientId: 20 },
  { comboId: 129, ingredientId: 25 },
  { comboId: 129, ingredientId: 64 },
];

export async function up(sql: Sql) {
  for (const ingredientCombo of ingredientComboPairs) {
    await sql`
      INSERT INTO
        ingredient_combos (
          combo_id,
          ingredient_id
        )
      VALUES
        (
          ${ingredientCombo.comboId},
          ${ingredientCombo.ingredientId}
        )
    `;
  }
}

export async function down(sql: Sql) {
  for (const ingredientCombo of ingredientComboPairs) {
    await sql`
      DELETE FROM ingredient_combos
      WHERE
        id = ${ingredientCombo.comboId}
    `;
  }
}
